### ISSUE TITLE
During API Creation, Amplify CLI Appears to Hang Until Editor is Closed

### ISSUE THREAD

**Issue by trevorrobertsjr** [awslabs/aws-amplify-unicorntrivia-workshop#12]
Please update instructions to warn users that they may need to close their editor after editing and saving their GraphQL code. Otherwise, the Amplify CLI appears to hang.

**Comment by wizage** [comment]
This is a know bug in Amplify CLI found here: aws-amplify/amplify-cli#429

Will update the docs to reflect that if the CLI is hanging you have to manually quit the editor.

Thanks for helping!
