### ISSUE TITLE
New Prompt within GraphQL Generation Docs

### ISSUE THREAD

**Issue by Kejixu** [awslabs/aws-amplify-unicorntrivia-workshop#6]
Within https://github.com/awslabs/aws-amplify-unicorntrivia-workshop/blob/master/documentation/admin_panel_doc.md

There's an additional prompt when setting up Admin Panel in regards to max statement depth

<img width="563" alt="Screen Shot 2019-08-15 at 11 18 35 AM" src="https://user-images.githubusercontent.com/1282860/63116606-ed3c0a00-bf4e-11e9-96fa-a99c3300b8b3.png">

**Comment by wizage** [comment]
@axptwig This should be the root issue. Can you update the screenshots. Thanks!

**Comment by axptwig** [comment]
issue is no longer up to date
